# Generated by Django 2.0.4 on 2018-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa dania')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Odnośnik')),
                ('text', models.TextField(verbose_name='Opis')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Danie',
                'verbose_name_plural': 'Dania',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Tytuł karty')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Odnośnik')),
                ('icon', models.ImageField(blank=True, upload_to='icons', verbose_name='Ikonka Kategorii')),
                ('text', models.TextField(verbose_name='Opis')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Karty',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='menus',
            field=models.ManyToManyField(to='app.Menu', verbose_name='Karta'),
        ),
    ]
