# Generated by Django 2.0.4 on 2018-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tytuł karty menu'),
        ),
    ]
